### PR TITLE
trivial updates

### PR DESCRIPTION
**Pull request by ungoldman**
- use screenshots directly from repos
- use more markdown

### CODE REVIEW

**Review by bcomnes — APPROVED** [review]
Only issue is it makes the GH-rendering look bad, but if you prefer it this way thats fine.

**Comment by ungoldman** [comment]
Ah, bummer. Didn't see that before pushing it up. Will try fiddling with it a bit more before merging.

**Comment by bcomnes** [comment]
Honestly, I'd be willing to try this for a while to error on the side of maintainability.

**Comment by bcomnes** [comment]
Gonna merge these as is.

**Pull request merged**
